backend:
  name: git-gateway
  branch: feature/blog
media_folder: public/img
public_folder: img
collections:
  - label: 'Blog'
    name: 'blog'
    folder: 'src/content/blogPosts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Titre', name: 'title', widget: 'string', required: true }
      - { label: 'Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
