name: CD
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy https://paulintrognon.fr
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        USERNAME: ${{ secrets.DEPLOY_USERNAME }}
        PORT: ${{ secrets.DEPLOY_PORT }}
        KEY: ${{ secrets.DEPLOY_SSHKEY }}
        script: ./deploy.sh
