name: CI
on:
  push:
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.json'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn lint .
    - name: Run TypeScript Checks
      run: yarn type-check
    - name: Run tests
      run: yarn test
